# Generated by Django 3.0.7 on 2021-11-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
    ]
